apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: neural-network
  namespace: '937651835502'
  selfLink: /apis/serving.knative.dev/v1/namespaces/937651835502/services/simplex
  uid: 835568dc-48d6-4378-99d0-d3354247c70a
  resourceVersion: AAXuziORK28
  generation: 8
  creationTimestamp: '2022-12-01T19:37:36.964825Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 08900a0c-f81d-4eb5-b5b0-d8afa92eb797
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: machkouroke@gmail.com
    serving.knative.dev/lastModifier: machkouroke@gmail.com
    client.knative.dev/user-image: gcr.io/lopsimplex/neural-network:latest
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '2'
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 937651835502-compute@developer.gserviceaccount.com
      containers:
        - image: gcr.io/lopsimplex/neural-network:latest
          ports:
            - name: http1
              containerPort: 8000
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 8
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2022-12-02T01:20:10.943343Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2022-12-02T01:20:03.620085Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2022-12-02T01:20:10.943343Z'
